const KW = {
  // EXPECTATION: did experience meet the promise?
  expect: {
    pos: [
      "life-altering",
      "unforgettable",
      "exceeded every expectation",
      "exceeded my expectations",
      "exceeded expectations",
      "truly exceptional",
      "utterly exceptional",
      "absolutely exceptional",
      "beyond delicious",
      "to die for",
      "flawless",
      "lives up to the hype",
      "worth the hype",
      "worth every resy",
      "worth every click",
      "completely rewired",
      "pure art",
      "love letter",
      "best dining experience",
      "one of the best",
      "best meal",
      "best kbbq",
      "best i",
      "phenomenal",
      "outstanding",
      "impeccable",
      "exceptional",
      "remarkable",
      "extraordinary",
      "top-tier",
      "top notch",
      "must-try",
      "highly recommend",
      "100% worth it",
      "so worth",
      "worth it if you can",
      "well worth the investment",
      "justifies the cost",
      "earned the michelin star",
      "deserving of",
      "michelin standards",
      "lives up to",
      "rewired my standards",
      "built for pleasure",
      "meaningful gift",
      "moment of humanity",
      "genuine warmth",
      "treated.*amazingly",
      "absolutely amazing",
      "fantastic",
      "wonderful",
      "sumptuous",
      "rich",
      "flavorful",
      "perfectly paced",
      "perfectly marbled",
      "expertly sourced",
      "expertly grilled",
      "expertly prepared",
      "expertly crafted",
      "cooked perfectly",
      "grilled to perfection",
      "cooked to perfection",
      "executed with precision",
      "single most flawless",
      "precision.*flavor.*skill",
      "curated",
      "high level",
      "exceptional quality",
      "top quality",
      "superb",
      "impressive",
      "beautiful",
      "incredible",
      "amazing service",
      "above and beyond",
      "attentive",
      "supportive",
      "professional",
      "elevated",
      "unique experience",
      "refreshing",
      "memorable",
      "creative",
      "intentional",
      "comfortable",
      "opposite of pretentious",
      "respects the diner",
      "holiday memory",
    ],
    neg: [
      "not worth the hype",
      "fell short",
      "underwhelmed",
      "disappointing",
      "deeply disappointing",
      "mediocre",
      "overhyped",
      "nothing special",
      "below expectations",
      "not what i expected",
      "not in par",
      "nowhere near michelin",
      "not deserving of",
      "below average",
      "hype was greater",
      "as usual the hype",
      "nothing wowed",
      "no wow factor",
      "looked better than it tasted",
      "pretty mid",
      "over-rated",
      "overrated",
      "far overrated",
      "not a bad experience but",
      "not like the one and only",
      "at best its a 2",
      "gotten a lot worse",
      "quality seems to have",
      "subpar",
      "fallen victim",
      "not particularly worth",
      "not that amazing",
      "not amazing for the price",
      "least favorite",
      "regretted ordering",
      "super salty",
      "unbalanced",
      "heavy and oily",
      "not very flavorful",
      "hard and not fresh",
      "nothing impressive",
      "hard to comprehend",
      "food may have been decent",
      "service ruined",
      "quality of fried chicken.*expect at popeyes",
      "not fresh",
      "decent but",
      "better kbbq",
      "better korean bbq",
      "similar.*lower",
    ],
    rage: [
      "complete waste",
      "worst place",
      "laughable experience",
      "terrible experience",
      "unacceptable experience",
      "worst.*spent",
      "don't be fooled",
      "i was wrong",
      "greedy business",
      "monthly car payment",
      "scammer",
      "con artist",
      "3x the price",
      "marred",
      "ruined everything",
      "absolutely no innovation",
      "travesty",
    ],
  },

  // PRICE: was the money worth it?
  price: {
    pos: [
      "worth every",
      "worth it",
      "great value",
      "well worth",
      "value for",
      "such good value",
      "worth the money",
      "worth the visit",
      "worth the investment",
      "worth the struggle",
      "worth coming",
      "worth the price",
      "worth spending",
      "worth the cost",
      "reasonably priced",
      "very reasonable",
      "fairly reasonable",
      "pretty cheap",
      "affordable",
      "fantastic deal",
      "fantastic deal",
      "not expensive",
      "prices aren't expensive",
      "good experience and generous portion",
      "you really get what you pay for",
      "bang for your buck",
      "get what you pay",
      "paying for the experience",
      "pricey but worth",
      "pricey, yes, but worth",
      "pricey, but absolutely worth",
      "splurge but",
      "price is high.*but",
      "on the pricier side.*but.*experience",
      "full package",
      "generous portion",
      "lot of food",
      "more of an experience",
      "quality justifies",
      "experience.*justifies",
      "unique blend",
      "undeniably a splurge",
      "saved up specifically",
      "make it well worth",
      "definitely worth",
      "great spot.*worth",
      "100% come back",
      "would come back",
      "will return",
      "definitely return",
      "highly recommend",
      "must visit",
    ],
    neg: [
      "overpriced",
      "over-priced",
      "over priced",
      "not worth the price",
      "not worth the money",
      "not worth what",
      "too expensive",
      "way overpriced",
      "waste of money",
      "wasted.*money",
      "waste.*dollars",
      "spent.*nothing",
      "not worth spending",
      "paying a premium",
      "charge as much",
      "for what they charge",
      "for what you get",
      "for what you end up getting",
      "for what we received",
      "price point.*disappointing",
      "price.*disappointing",
      "price tag",
      "high price tag",
      "high price point",
      "high cost",
      "expensive dinner",
      "premium prices",
      "charge premium",
      "charges as much",
      "charges.*much",
      "pricier side",
      "pricey to an extent",
      "pricey for what",
      "not worth the high",
      "food isn't that amazing for the price",
      "doesn't seem fair for the price",
      "better.*lower budget",
      "similar kbbq.*lower budget",
      "money could be saved",
      "spent better elsewhere",
      "taking my business elsewhere",
      "don't waste your money",
      "never spending.*here",
      "wouldn't have cared",
      "i think the price is worth it.*but",
      "i don't think the price is worth it",
      "minimum spend",
      "came out close to.*each",
      "without the overpriced tag",
      "spending good money",
      "for a bill that was over",
      "underwhelmed for a bill",
      "hard to get a reservation.*if.*worth",
      "struggle.*worth the",
      "difficult to get.*why",
      "obtaining.*near impossibility",
      "spent about.*went home.*empty",
      "almost.*on a dinner",
      "at least make it memorable",
      "don't get the bang for your buck",
      "can't expect much",
      "fell like a complete waste",
      "charge you.*more",
      "$225.*should guarantee",
      "over.*for what",
      "complete waste of money",
      "laughable.*for.*person",
    ],
    rage: [
      "complete waste of money",
      "extortion",
      "robbery",
      "scam",
      "total rip",
      "worst.*money.*spent",
      "worst.*spent",
      "laughable.*price",
      "monthly car payment",
      "charged.*without",
      "attempt to charge",
      "very concerning.*charge",
      "con artist",
      "3x the price",
      "wasted \$200",
      "wasted.*hundred",
      "we wasted",
      "greedy business practices",
      "weird scammer move",
      "unfair",
      "doesn't seem fair",
    ],
  },

  // SERVICE: how were you treated?
  service: {
    pos: [
      "above and beyond",
      "impeccable service",
      "phenomenal service",
      "exceptional service",
      "wonderful service",
      "excellent service",
      "amazing service",
      "fantastic service",
      "great service",
      "attentive",
      "impressively attentive",
      "incredibly attentive",
      "extremely attentive",
      "without feeling rushed",
      "perfectly paced",
      "timing was perfect",
      "knowledgeable",
      "well-coordinated",
      "professional",
      "welcoming",
      "warm",
      "genuine warmth",
      "kindness",
      "kind",
      "treated me amazingly",
      "treated.*amazingly",
      "goes above",
      "absolute angels",
      "1000/10 service",
      "truly welcomed",
      "elevated and welcoming",
      "new york-style hospitality",
      "hospitality",
      "incredibly professional",
      "staff was.*amazing",
      "service and drinks and food were amazing",
      "supportive",
      "throughout the entire",
      "helpful",
      "thoughtful",
      "responsive",
      "accommodating",
      "patient",
      "caring",
      "respectful",
      "seamless",
      "well-timed",
      "felt taken care",
      "felt welcomed",
      "made us feel",
      "high-quality service",
      "A1",
      "excellent across the board",
      "fantastic across the board",
    ],
    neg: [
      "rude",
      "ignored",
      "inattentive",
      "unattended",
      "left unattended",
      "very unattended",
      "rushed",
      "everything felt rushed",
      "robot-like",
      "cold service",
      "unprofessional",
      "terrible service",
      "bad service",
      "poor service",
      "subpar service",
      "disappointing service",
      "service left us",
      "service was.*disappointing",
      "service ruined",
      "service was nowhere near",
      "not patient",
      "not very patient",
      "not on par with",
      "below-average service",
      "service was too long",
      "missing items",
      "not properly",
      "hard to call it proper service",
      "lack of customer service",
      "poor attitude",
      "unresponsive",
      "would not recommend",
      "difficult to get",
      "hard to acquire reservation",
      "exclusivity",
      "service marred",
      "marred an expensive",
      "cut off",
      "quite disappointing",
      "more than disappointing",
      "left.*disappointed",
      "service fell short",
      "service didn't match",
      "below.*expected",
      "forgot",
      "overlooked",
      "dismissive",
      "indifferent",
      "impersonal",
      "left waiting",
      "made.*wait",
      "couldn't get attention",
      "felt ignored",
      "rushed at the end",
      "rush job",
      "poured.*shallow",
      "weird.*move",
    ],
    rage: [
      "racist",
      "discrimination",
      "humiliated",
      "disrespectful",
      "degrading",
      "insulting",
      "making assumptions about a guest",
      "assumptions about.*worthiness",
      "white dollar is worth more",
      "white dollar worth more",
      "think they're too good",
      "too good for the common",
      "greedy",
      "inappropriate and shortsighted",
      "kicked out",
      "deeply disappointing",
      "unacceptable",
      "completely unacceptable",
      "absolute lack",
      "zero service",
      "staff was rude",
      "extremely rude",
      "treated like",
      "made to feel",
      "hostile",
      "aggressive",
      "condescending",
    ],
  },

  // HUNGER / PORTION: did you leave satisfied?
  hunger: {
    pos: [
      "left full",
      "so full",
      "stuffed",
      "a lot of food",
      "lot of food for two",
      "abundance",
      "generous portions",
      "generous portion",
      "more than enough",
      "very full",
      "you leave full",
      "leave full",
      "overwhelmed.*full",
      "portions are generous",
      "taste and portions are generous",
      "full package",
      "came out.*full",
      "incredibly satisfying",
      "satisfying",
      "satisfy",
      "satisfied",
      "filling",
    ],
    neg: [
      "left hungry",
      "went home hungry",
      "went home on an empty",
      "still hungry",
      "small portions",
      "portions were small",
      "portions were.*smaller",
      "portion very small",
      "tiny portions",
      "the portion was tiny",
      "barely any meat",
      "not enough food",
      "hardly any meat",
      "comes with hardly any meat",
      "only get 2 small cuts",
      "sides for 1 person",
      "portions were ridiculous",
      "small for the price",
      "smaller than expected",
      "bit on the smaller side",
      "didn't want to waste.*money",
      "kept eating.*waste",
      "get full of the side cheap stuff",
      "portions.*on the smaller side",
      "little amount",
      "very little",
      "amount.*same as",
      "same amount of food",
      "stopped at burger king",
      "portions of meat were small",
      "not very filling",
      "wished there was more",
    ],
    rage: [
      "starving",
      "empty stomach",
      "angry and hungry",
      "came away.*hungry",
      "left severely disappointed.*hungry",
      "paid.*hungry",
      "spent.*hungry",
      "we left hungry",
      "you still leave hungry",
      "went home on an empty stomach",
      "ate nothing but",
      "wasted.*ate nothing",
    ],
  },

  // OVERALL VALUE: experience vs cost synthesis
  value: {
    pos: [
      "worth the splurge",
      "worth the wait",
      "worth the struggle",
      "worth the reservation",
      "worth coming back",
      "worth every penny",
      "worth every bite",
      "worth every dollar",
      "would come back",
      "will come back",
      "can't wait to go back",
      "going back",
      "already returned",
      "will return",
      "definitely return",
      "we will definitely",
      "highly recommend",
      "would recommend",
      "recommend to anyone",
      "must visit",
      "must try",
      "must go",
      "must book",
      "book it",
      "go if you can",
      "justified by",
      "justified the cost",
      "justifies everything",
      "money well spent",
      "money is well spent",
      "well spent",
      "experience is worth",
      "dining experience is worth",
      "quality justifies",
      "quality more than makes up",
      "100% worth it",
      "so worth",
      "absolutely worth",
      "definitely worth",
      "worth every resy",
      "worth every click",
      "worth the investment",
      "pricey but worth",
      "splurge but worth",
      "price is high but",
      "understand why",
      "earned the michelin",
      "deserves",
      "deserving",
      "definitely a staple",
      "definitely understand why",
      "reservations are hard.*but.*worth",
    ],
    neg: [
      "wouldn't return",
      "won't return",
      "won't be back",
      "will not be back",
      "won't go back",
      "would not go back",
      "not going back",
      "never going back",
      "not coming back",
      "won't come back",
      "won't recommend",
      "wouldn't recommend",
      "can't recommend",
      "i do not recommend",
      "would not recommend",
      "taking my business elsewhere",
      "find a different",
      "go somewhere else",
      "better options",
      "better places",
      "better kbbq",
      "better korean bbq",
      "better.*for the price",
      "better value",
      "more value",
      "more for your money",
      "for this price",
      "at this price point",
      "at these prices",
      "shame",
      "what a shame",
      "unfortunately",
      "ruined by",
      "let down",
      "left disappointed",
      "left with a sour",
      "sour note",
      "sour taste",
      "not the same",
      "not as good as before",
      "declined",
      "has declined",
      "gone downhill",
      "has gone downhill",
      "used to be better",
      "used to be amazing",
      "not what it used to be",
      "not worth.*struggle",
      "hard to get.*wonder if",
      "obtaining.*impossibility",
      "hype was greater",
      "as usual the hype",
      "nothing wowed",
      "don't waste your money",
      "not worth",
      "wouldn't have cared",
      "better.*lower budget",
      "similar.*lower",
      "patronize another",
      "i can see the appeal to non-koreans",
    ],
    rage: [
      "never again",
      "absolute disgrace",
      "complete disgrace",
      "utterly disgraceful",
      "should be ashamed",
      "how dare",
      "unacceptable",
      "completely unacceptable",
      "deeply unacceptable",
      "total disaster",
      "absolute disaster",
      "disaster of",
      "do not go",
      "do not eat",
      "stay away",
      "avoid this",
      "avoid at all costs",
      "warn everyone",
      "warning to others",
      "beware",
      "be careful",
      "be warned",
      "don't be fooled",
      "fallen victim",
      "greedy business",
    ],
  },
};
